// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

type Route struct {
	ID               string
	LongName         string
	ShortName        string
	Description      string
	SelectBusService bool
}
